color0 #474459
color1 #ffb4ab
color2 #89ceff
color3 #94cdf7
color4 #c6bfff
color5 #89ceff
color6 #94cdf7
color7 #e5e0ef
color8 #928ea5
color9 #ffb4ab
color10 #89ceff
color11 #94cdf7
color12 #c6bfff
color13 #89ceff
color14 #94cdf7
color15 #e5e0ef

cursor                #e5e0ef
cursor_text_color     #13121c
background            #13121c
foreground            #e5e0ef
selection_foreground  #c8c3dc
selection_background  #474459
active_border_color   #89ceff
inactive_border_color #474459
url_color             #89ceff

active_tab_foreground   #00344d
active_tab_background   #89ceff
inactive_tab_foreground #c8c3dc
inactive_tab_background #474459
cursor_trail_color      #c8c3dc
