[Appearance]
color_scheme_path=/home/sharwesh/Modules/nixos/rice/Dotfiles/qt5ct/colors/rice.conf
custom_palette=true
style=Fusion

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2Q\0\0\0\xe8\0\0\x5/\0\0\x3o\0\0\x2Q\0\0\x1\r\0\0\x5/\0\0\x3o\0\0\0\0\0\0\0\0\a\x80\0\0\x2Q\0\0\x1\r\0\0\x5/\0\0\x3o)
