// Generated from unicode-emoji 17.0 emoji-test.txt (fully-qualified, no skin-tone variants).
.pragma library

var groups = ["Smileys & Emotion", "People & Body", "Animals & Nature", "Food & Drink", "Travel & Places", "Activities", "Objects", "Symbols", "Flags"];

// [emoji, name, group index]
var list = [
["😀", "grinning face", 0],
["😃", "grinning face with big eyes", 0],
["😄", "grinning face with smiling eyes", 0],
["😁", "beaming face with smiling eyes", 0],
["😆", "grinning squinting face", 0],
["😅", "grinning face with sweat", 0],
["🤣", "rolling on the floor laughing", 0],
["😂", "face with tears of joy", 0],
["🙂", "slightly smiling face", 0],
["🙃", "upside-down face", 0],
["🫠", "melting face", 0],
["😉", "winking face", 0],
["😊", "smiling face with smiling eyes", 0],
["😇", "smiling face with halo", 0],
["🥰", "smiling face with hearts", 0],
["😍", "smiling face with heart-eyes", 0],
["🤩", "star-struck", 0],
["😘", "face blowing a kiss", 0],
["😗", "kissing face", 0],
["☺️", "smiling face", 0],
["😚", "kissing face with closed eyes", 0],
["😙", "kissing face with smiling eyes", 0],
["🥲", "smiling face with tear", 0],
["😋", "face savoring food", 0],
["😛", "face with tongue", 0],
["😜", "winking face with tongue", 0],
["🤪", "zany face", 0],
["😝", "squinting face with tongue", 0],
["🤑", "money-mouth face", 0],
["🤗", "smiling face with open hands", 0],
["🤭", "face with hand over mouth", 0],
["🫢", "face with open eyes and hand over mouth", 0],
["🫣", "face with peeking eye", 0],
["🤫", "shushing face", 0],
["🤔", "thinking face", 0],
["🫡", "saluting face", 0],
["🤐", "zipper-mouth face", 0],
["🤨", "face with raised eyebrow", 0],
["😐", "neutral face", 0],
["😑", "expressionless face", 0],
["😶", "face without mouth", 0],
["🫥", "dotted line face", 0],
["😶‍🌫️", "face in clouds", 0],
["😏", "smirking face", 0],
["😒", "unamused face", 0],
["🙄", "face with rolling eyes", 0],
["😬", "grimacing face", 0],
["😮‍💨", "face exhaling", 0],
["🤥", "lying face", 0],
["🫨", "shaking face", 0],
["🙂‍↔️", "head shaking horizontally", 0],
["🙂‍↕️", "head shaking vertically", 0],
["😌", "relieved face", 0],
["😔", "pensive face", 0],
["😪", "sleepy face", 0],
["🤤", "drooling face", 0],
["😴", "sleeping face", 0],
["🫩", "face with bags under eyes", 0],
["😷", "face with medical mask", 0],
["🤒", "face with thermometer", 0],
["🤕", "face with head-bandage", 0],
["🤢", "nauseated face", 0],
["🤮", "face vomiting", 0],
["🤧", "sneezing face", 0],
["🥵", "hot face", 0],
["🥶", "cold face", 0],
["🥴", "woozy face", 0],
["😵", "face with crossed-out eyes", 0],
["😵‍💫", "face with spiral eyes", 0],
["🤯", "exploding head", 0],
["🤠", "cowboy hat face", 0],
["🥳", "partying face", 0],
["🥸", "disguised face", 0],
["😎", "smiling face with sunglasses", 0],
["🤓", "nerd face", 0],
["🧐", "face with monocle", 0],
["😕", "confused face", 0],
["🫤", "face with diagonal mouth", 0],
["😟", "worried face", 0],
["🙁", "slightly frowning face", 0],
["☹️", "frowning face", 0],
["😮", "face with open mouth", 0],
["😯", "hushed face", 0],
["😲", "astonished face", 0],
["😳", "flushed face", 0],
["🫪", "distorted face", 0],
["🥺", "pleading face", 0],
["🥹", "face holding back tears", 0],
["😦", "frowning face with open mouth", 0],
["😧", "anguished face", 0],
["😨", "fearful face", 0],
["😰", "anxious face with sweat", 0],
["😥", "sad but relieved face", 0],
["😢", "crying face", 0],
["😭", "loudly crying face", 0],
["😱", "face screaming in fear", 0],
["😖", "confounded face", 0],
["😣", "persevering face", 0],
["😞", "disappointed face", 0],
["😓", "downcast face with sweat", 0],
["😩", "weary face", 0],
["😫", "tired face", 0],
["🥱", "yawning face", 0],
["😤", "face with steam from nose", 0],
["😡", "enraged face", 0],
["😠", "angry face", 0],
["🤬", "face with symbols on mouth", 0],
["😈", "smiling face with horns", 0],
["👿", "angry face with horns", 0],
["💀", "skull", 0],
["☠️", "skull and crossbones", 0],
["💩", "pile of poo", 0],
["🤡", "clown face", 0],
["👹", "ogre", 0],
["👺", "goblin", 0],
["👻", "ghost", 0],
["👽", "alien", 0],
["👾", "alien monster", 0],
["🤖", "robot", 0],
["😺", "grinning cat", 0],
["😸", "grinning cat with smiling eyes", 0],
["😹", "cat with tears of joy", 0],
["😻", "smiling cat with heart-eyes", 0],
["😼", "cat with wry smile", 0],
["😽", "kissing cat", 0],
["🙀", "weary cat", 0],
["😿", "crying cat", 0],
["😾", "pouting cat", 0],
["🙈", "see-no-evil monkey", 0],
["🙉", "hear-no-evil monkey", 0],
["🙊", "speak-no-evil monkey", 0],
["💌", "love letter", 0],
["💘", "heart with arrow", 0],
["💝", "heart with ribbon", 0],
["💖", "sparkling heart", 0],
["💗", "growing heart", 0],
["💓", "beating heart", 0],
["💞", "revolving hearts", 0],
["💕", "two hearts", 0],
["💟", "heart decoration", 0],
["❣️", "heart exclamation", 0],
["💔", "broken heart", 0],
["❤️‍🔥", "heart on fire", 0],
["❤️‍🩹", "mending heart", 0],
["❤️", "red heart", 0],
["🩷", "pink heart", 0],
["🧡", "orange heart", 0],
["💛", "yellow heart", 0],
["💚", "green heart", 0],
["💙", "blue heart", 0],
["🩵", "light blue heart", 0],
["💜", "purple heart", 0],
["🤎", "brown heart", 0],
["🖤", "black heart", 0],
["🩶", "grey heart", 0],
["🤍", "white heart", 0],
["💋", "kiss mark", 0],
["💯", "hundred points", 0],
["💢", "anger symbol", 0],
["🫯", "fight cloud", 0],
["💥", "collision", 0],
["💫", "dizzy", 0],
["💦", "sweat droplets", 0],
["💨", "dashing away", 0],
["🕳️", "hole", 0],
["💬", "speech balloon", 0],
["👁️‍🗨️", "eye in speech bubble", 0],
["🗨️", "left speech bubble", 0],
["🗯️", "right anger bubble", 0],
["💭", "thought balloon", 0],
["💤", "ZZZ", 0],
["👋", "waving hand", 1],
["🤚", "raised back of hand", 1],
["🖐️", "hand with fingers splayed", 1],
["✋", "raised hand", 1],
["🖖", "vulcan salute", 1],
["🫱", "rightwards hand", 1],
["🫲", "leftwards hand", 1],
["🫳", "palm down hand", 1],
["🫴", "palm up hand", 1],
["🫷", "leftwards pushing hand", 1],
["🫸", "rightwards pushing hand", 1],
["👌", "OK hand", 1],
["🤌", "pinched fingers", 1],
["🤏", "pinching hand", 1],
["✌️", "victory hand", 1],
["🤞", "crossed fingers", 1],
["🫰", "hand with index finger and thumb crossed", 1],
["🤟", "love-you gesture", 1],
["🤘", "sign of the horns", 1],
["🤙", "call me hand", 1],
["👈", "backhand index pointing left", 1],
["👉", "backhand index pointing right", 1],
["👆", "backhand index pointing up", 1],
["🖕", "middle finger", 1],
["👇", "backhand index pointing down", 1],
["☝️", "index pointing up", 1],
["🫵", "index pointing at the viewer", 1],
["👍", "thumbs up", 1],
["👎", "thumbs down", 1],
["✊", "raised fist", 1],
["👊", "oncoming fist", 1],
["🤛", "left-facing fist", 1],
["🤜", "right-facing fist", 1],
["👏", "clapping hands", 1],
["🙌", "raising hands", 1],
["🫶", "heart hands", 1],
["👐", "open hands", 1],
["🤲", "palms up together", 1],
["🤝", "handshake", 1],
["🙏", "folded hands", 1],
["✍️", "writing hand", 1],
["💅", "nail polish", 1],
["🤳", "selfie", 1],
["💪", "flexed biceps", 1],
["🦾", "mechanical arm", 1],
["🦿", "mechanical leg", 1],
["🦵", "leg", 1],
["🦶", "foot", 1],
["👂", "ear", 1],
["🦻", "ear with hearing aid", 1],
["👃", "nose", 1],
["🧠", "brain", 1],
["🫀", "anatomical heart", 1],
["🫁", "lungs", 1],
["🦷", "tooth", 1],
["🦴", "bone", 1],
["👀", "eyes", 1],
["👁️", "eye", 1],
["👅", "tongue", 1],
["👄", "mouth", 1],
["🫦", "biting lip", 1],
["👶", "baby", 1],
["🧒", "child", 1],
["👦", "boy", 1],
["👧", "girl", 1],
["🧑", "person", 1],
["👱", "person: blond hair", 1],
["👨", "man", 1],
["🧔", "person: beard", 1],
["🧔‍♂️", "man: beard", 1],
["🧔‍♀️", "woman: beard", 1],
["👨‍🦰", "man: red hair", 1],
["👨‍🦱", "man: curly hair", 1],
["👨‍🦳", "man: white hair", 1],
["👨‍🦲", "man: bald", 1],
["👩", "woman", 1],
["👩‍🦰", "woman: red hair", 1],
["🧑‍🦰", "person: red hair", 1],
["👩‍🦱", "woman: curly hair", 1],
["🧑‍🦱", "person: curly hair", 1],
["👩‍🦳", "woman: white hair", 1],
["🧑‍🦳", "person: white hair", 1],
["👩‍🦲", "woman: bald", 1],
["🧑‍🦲", "person: bald", 1],
["👱‍♀️", "woman: blond hair", 1],
["👱‍♂️", "man: blond hair", 1],
["🧓", "older person", 1],
["👴", "old man", 1],
["👵", "old woman", 1],
["🙍", "person frowning", 1],
["🙍‍♂️", "man frowning", 1],
["🙍‍♀️", "woman frowning", 1],
["🙎", "person pouting", 1],
["🙎‍♂️", "man pouting", 1],
["🙎‍♀️", "woman pouting", 1],
["🙅", "person gesturing NO", 1],
["🙅‍♂️", "man gesturing NO", 1],
["🙅‍♀️", "woman gesturing NO", 1],
["🙆", "person gesturing OK", 1],
["🙆‍♂️", "man gesturing OK", 1],
["🙆‍♀️", "woman gesturing OK", 1],
["💁", "person tipping hand", 1],
["💁‍♂️", "man tipping hand", 1],
["💁‍♀️", "woman tipping hand", 1],
["🙋", "person raising hand", 1],
["🙋‍♂️", "man raising hand", 1],
["🙋‍♀️", "woman raising hand", 1],
["🧏", "deaf person", 1],
["🧏‍♂️", "deaf man", 1],
["🧏‍♀️", "deaf woman", 1],
["🙇", "person bowing", 1],
["🙇‍♂️", "man bowing", 1],
["🙇‍♀️", "woman bowing", 1],
["🤦", "person facepalming", 1],
["🤦‍♂️", "man facepalming", 1],
["🤦‍♀️", "woman facepalming", 1],
["🤷", "person shrugging", 1],
["🤷‍♂️", "man shrugging", 1],
["🤷‍♀️", "woman shrugging", 1],
["🧑‍⚕️", "health worker", 1],
["👨‍⚕️", "man health worker", 1],
["👩‍⚕️", "woman health worker", 1],
["🧑‍🎓", "student", 1],
["👨‍🎓", "man student", 1],
["👩‍🎓", "woman student", 1],
["🧑‍🏫", "teacher", 1],
["👨‍🏫", "man teacher", 1],
["👩‍🏫", "woman teacher", 1],
["🧑‍⚖️", "judge", 1],
["👨‍⚖️", "man judge", 1],
["👩‍⚖️", "woman judge", 1],
["🧑‍🌾", "farmer", 1],
["👨‍🌾", "man farmer", 1],
["👩‍🌾", "woman farmer", 1],
["🧑‍🍳", "cook", 1],
["👨‍🍳", "man cook", 1],
["👩‍🍳", "woman cook", 1],
["🧑‍🔧", "mechanic", 1],
["👨‍🔧", "man mechanic", 1],
["👩‍🔧", "woman mechanic", 1],
["🧑‍🏭", "factory worker", 1],
["👨‍🏭", "man factory worker", 1],
["👩‍🏭", "woman factory worker", 1],
["🧑‍💼", "office worker", 1],
["👨‍💼", "man office worker", 1],
["👩‍💼", "woman office worker", 1],
["🧑‍🔬", "scientist", 1],
["👨‍🔬", "man scientist", 1],
["👩‍🔬", "woman scientist", 1],
["🧑‍💻", "technologist", 1],
["👨‍💻", "man technologist", 1],
["👩‍💻", "woman technologist", 1],
["🧑‍🎤", "singer", 1],
["👨‍🎤", "man singer", 1],
["👩‍🎤", "woman singer", 1],
["🧑‍🎨", "artist", 1],
["👨‍🎨", "man artist", 1],
["👩‍🎨", "woman artist", 1],
["🧑‍✈️", "pilot", 1],
["👨‍✈️", "man pilot", 1],
["👩‍✈️", "woman pilot", 1],
["🧑‍🚀", "astronaut", 1],
["👨‍🚀", "man astronaut", 1],
["👩‍🚀", "woman astronaut", 1],
["🧑‍🚒", "firefighter", 1],
["👨‍🚒", "man firefighter", 1],
["👩‍🚒", "woman firefighter", 1],
["👮", "police officer", 1],
["👮‍♂️", "man police officer", 1],
["👮‍♀️", "woman police officer", 1],
["🕵️", "detective", 1],
["🕵️‍♂️", "man detective", 1],
["🕵️‍♀️", "woman detective", 1],
["💂", "guard", 1],
["💂‍♂️", "man guard", 1],
["💂‍♀️", "woman guard", 1],
["🥷", "ninja", 1],
["👷", "construction worker", 1],
["👷‍♂️", "man construction worker", 1],
["👷‍♀️", "woman construction worker", 1],
["🫅", "person with crown", 1],
["🤴", "prince", 1],
["👸", "princess", 1],
["👳", "person wearing turban", 1],
["👳‍♂️", "man wearing turban", 1],
["👳‍♀️", "woman wearing turban", 1],
["👲", "person with skullcap", 1],
["🧕", "woman with headscarf", 1],
["🤵", "person in tuxedo", 1],
["🤵‍♂️", "man in tuxedo", 1],
["🤵‍♀️", "woman in tuxedo", 1],
["👰", "person with veil", 1],
["👰‍♂️", "man with veil", 1],
["👰‍♀️", "woman with veil", 1],
["🤰", "pregnant woman", 1],
["🫃", "pregnant man", 1],
["🫄", "pregnant person", 1],
["🤱", "breast-feeding", 1],
["👩‍🍼", "woman feeding baby", 1],
["👨‍🍼", "man feeding baby", 1],
["🧑‍🍼", "person feeding baby", 1],
["👼", "baby angel", 1],
["🎅", "Santa Claus", 1],
["🤶", "Mrs. Claus", 1],
["🧑‍🎄", "Mx Claus", 1],
["🦸", "superhero", 1],
["🦸‍♂️", "man superhero", 1],
["🦸‍♀️", "woman superhero", 1],
["🦹", "supervillain", 1],
["🦹‍♂️", "man supervillain", 1],
["🦹‍♀️", "woman supervillain", 1],
["🧙", "mage", 1],
["🧙‍♂️", "man mage", 1],
["🧙‍♀️", "woman mage", 1],
["🧚", "fairy", 1],
["🧚‍♂️", "man fairy", 1],
["🧚‍♀️", "woman fairy", 1],
["🧛", "vampire", 1],
["🧛‍♂️", "man vampire", 1],
["🧛‍♀️", "woman vampire", 1],
["🧜", "merperson", 1],
["🧜‍♂️", "merman", 1],
["🧜‍♀️", "mermaid", 1],
["🧝", "elf", 1],
["🧝‍♂️", "man elf", 1],
["🧝‍♀️", "woman elf", 1],
["🧞", "genie", 1],
["🧞‍♂️", "man genie", 1],
["🧞‍♀️", "woman genie", 1],
["🧟", "zombie", 1],
["🧟‍♂️", "man zombie", 1],
["🧟‍♀️", "woman zombie", 1],
["🧌", "troll", 1],
["🫈", "hairy creature", 1],
["💆", "person getting massage", 1],
["💆‍♂️", "man getting massage", 1],
["💆‍♀️", "woman getting massage", 1],
["💇", "person getting haircut", 1],
["💇‍♂️", "man getting haircut", 1],
["💇‍♀️", "woman getting haircut", 1],
["🚶", "person walking", 1],
["🚶‍♂️", "man walking", 1],
["🚶‍♀️", "woman walking", 1],
["🚶‍➡️", "person walking facing right", 1],
["🚶‍♀️‍➡️", "woman walking facing right", 1],
["🚶‍♂️‍➡️", "man walking facing right", 1],
["🧍", "person standing", 1],
["🧍‍♂️", "man standing", 1],
["🧍‍♀️", "woman standing", 1],
["🧎", "person kneeling", 1],
["🧎‍♂️", "man kneeling", 1],
["🧎‍♀️", "woman kneeling", 1],
["🧎‍➡️", "person kneeling facing right", 1],
["🧎‍♀️‍➡️", "woman kneeling facing right", 1],
["🧎‍♂️‍➡️", "man kneeling facing right", 1],
["🧑‍🦯", "person with white cane", 1],
["🧑‍🦯‍➡️", "person with white cane facing right", 1],
["👨‍🦯", "man with white cane", 1],
["👨‍🦯‍➡️", "man with white cane facing right", 1],
["👩‍🦯", "woman with white cane", 1],
["👩‍🦯‍➡️", "woman with white cane facing right", 1],
["🧑‍🦼", "person in motorized wheelchair", 1],
["🧑‍🦼‍➡️", "person in motorized wheelchair facing right", 1],
["👨‍🦼", "man in motorized wheelchair", 1],
["👨‍🦼‍➡️", "man in motorized wheelchair facing right", 1],
["👩‍🦼", "woman in motorized wheelchair", 1],
["👩‍🦼‍➡️", "woman in motorized wheelchair facing right", 1],
["🧑‍🦽", "person in manual wheelchair", 1],
["🧑‍🦽‍➡️", "person in manual wheelchair facing right", 1],
["👨‍🦽", "man in manual wheelchair", 1],
["👨‍🦽‍➡️", "man in manual wheelchair facing right", 1],
["👩‍🦽", "woman in manual wheelchair", 1],
["👩‍🦽‍➡️", "woman in manual wheelchair facing right", 1],
["🏃", "person running", 1],
["🏃‍♂️", "man running", 1],
["🏃‍♀️", "woman running", 1],
["🏃‍➡️", "person running facing right", 1],
["🏃‍♀️‍➡️", "woman running facing right", 1],
["🏃‍♂️‍➡️", "man running facing right", 1],
["🧑‍🩰", "ballet dancer", 1],
["💃", "woman dancing", 1],
["🕺", "man dancing", 1],
["🕴️", "person in suit levitating", 1],
["👯", "people with bunny ears", 1],
["👯‍♂️", "men with bunny ears", 1],
["👯‍♀️", "women with bunny ears", 1],
["🧖", "person in steamy room", 1],
["🧖‍♂️", "man in steamy room", 1],
["🧖‍♀️", "woman in steamy room", 1],
["🧗", "person climbing", 1],
["🧗‍♂️", "man climbing", 1],
["🧗‍♀️", "woman climbing", 1],
["🤺", "person fencing", 1],
["🏇", "horse racing", 1],
["⛷️", "skier", 1],
["🏂", "snowboarder", 1],
["🏌️", "person golfing", 1],
["🏌️‍♂️", "man golfing", 1],
["🏌️‍♀️", "woman golfing", 1],
["🏄", "person surfing", 1],
["🏄‍♂️", "man surfing", 1],
["🏄‍♀️", "woman surfing", 1],
["🚣", "person rowing boat", 1],
["🚣‍♂️", "man rowing boat", 1],
["🚣‍♀️", "woman rowing boat", 1],
["🏊", "person swimming", 1],
["🏊‍♂️", "man swimming", 1],
["🏊‍♀️", "woman swimming", 1],
["⛹️", "person bouncing ball", 1],
["⛹️‍♂️", "man bouncing ball", 1],
["⛹️‍♀️", "woman bouncing ball", 1],
["🏋️", "person lifting weights", 1],
["🏋️‍♂️", "man lifting weights", 1],
["🏋️‍♀️", "woman lifting weights", 1],
["🚴", "person biking", 1],
["🚴‍♂️", "man biking", 1],
["🚴‍♀️", "woman biking", 1],
["🚵", "person mountain biking", 1],
["🚵‍♂️", "man mountain biking", 1],
["🚵‍♀️", "woman mountain biking", 1],
["🤸", "person cartwheeling", 1],
["🤸‍♂️", "man cartwheeling", 1],
["🤸‍♀️", "woman cartwheeling", 1],
["🤼", "people wrestling", 1],
["🤼‍♂️", "men wrestling", 1],
["🤼‍♀️", "women wrestling", 1],
["🤽", "person playing water polo", 1],
["🤽‍♂️", "man playing water polo", 1],
["🤽‍♀️", "woman playing water polo", 1],
["🤾", "person playing handball", 1],
["🤾‍♂️", "man playing handball", 1],
["🤾‍♀️", "woman playing handball", 1],
["🤹", "person juggling", 1],
["🤹‍♂️", "man juggling", 1],
["🤹‍♀️", "woman juggling", 1],
["🧘", "person in lotus position", 1],
["🧘‍♂️", "man in lotus position", 1],
["🧘‍♀️", "woman in lotus position", 1],
["🛀", "person taking bath", 1],
["🛌", "person in bed", 1],
["🧑‍🤝‍🧑", "people holding hands", 1],
["👭", "women holding hands", 1],
["👫", "woman and man holding hands", 1],
["👬", "men holding hands", 1],
["💏", "kiss", 1],
["👩‍❤️‍💋‍👨", "kiss: woman, man", 1],
["👨‍❤️‍💋‍👨", "kiss: man, man", 1],
["👩‍❤️‍💋‍👩", "kiss: woman, woman", 1],
["💑", "couple with heart", 1],
["👩‍❤️‍👨", "couple with heart: woman, man", 1],
["👨‍❤️‍👨", "couple with heart: man, man", 1],
["👩‍❤️‍👩", "couple with heart: woman, woman", 1],
["👨‍👩‍👦", "family: man, woman, boy", 1],
["👨‍👩‍👧", "family: man, woman, girl", 1],
["👨‍👩‍👧‍👦", "family: man, woman, girl, boy", 1],
["👨‍👩‍👦‍👦", "family: man, woman, boy, boy", 1],
["👨‍👩‍👧‍👧", "family: man, woman, girl, girl", 1],
["👨‍👨‍👦", "family: man, man, boy", 1],
["👨‍👨‍👧", "family: man, man, girl", 1],
["👨‍👨‍👧‍👦", "family: man, man, girl, boy", 1],
["👨‍👨‍👦‍👦", "family: man, man, boy, boy", 1],
["👨‍👨‍👧‍👧", "family: man, man, girl, girl", 1],
["👩‍👩‍👦", "family: woman, woman, boy", 1],
["👩‍👩‍👧", "family: woman, woman, girl", 1],
["👩‍👩‍👧‍👦", "family: woman, woman, girl, boy", 1],
["👩‍👩‍👦‍👦", "family: woman, woman, boy, boy", 1],
["👩‍👩‍👧‍👧", "family: woman, woman, girl, girl", 1],
["👨‍👦", "family: man, boy", 1],
["👨‍👦‍👦", "family: man, boy, boy", 1],
["👨‍👧", "family: man, girl", 1],
["👨‍👧‍👦", "family: man, girl, boy", 1],
["👨‍👧‍👧", "family: man, girl, girl", 1],
["👩‍👦", "family: woman, boy", 1],
["👩‍👦‍👦", "family: woman, boy, boy", 1],
["👩‍👧", "family: woman, girl", 1],
["👩‍👧‍👦", "family: woman, girl, boy", 1],
["👩‍👧‍👧", "family: woman, girl, girl", 1],
["🗣️", "speaking head", 1],
["👤", "bust in silhouette", 1],
["👥", "busts in silhouette", 1],
["🫂", "people hugging", 1],
["👪", "family", 1],
["🧑‍🧑‍🧒", "family: adult, adult, child", 1],
["🧑‍🧑‍🧒‍🧒", "family: adult, adult, child, child", 1],
["🧑‍🧒", "family: adult, child", 1],
["🧑‍🧒‍🧒", "family: adult, child, child", 1],
["👣", "footprints", 1],
["🫆", "fingerprint", 1],
["🐵", "monkey face", 2],
["🐒", "monkey", 2],
["🦍", "gorilla", 2],
["🦧", "orangutan", 2],
["🐶", "dog face", 2],
["🐕", "dog", 2],
["🦮", "guide dog", 2],
["🐕‍🦺", "service dog", 2],
["🐩", "poodle", 2],
["🐺", "wolf", 2],
["🦊", "fox", 2],
["🦝", "raccoon", 2],
["🐱", "cat face", 2],
["🐈", "cat", 2],
["🐈‍⬛", "black cat", 2],
["🦁", "lion", 2],
["🐯", "tiger face", 2],
["🐅", "tiger", 2],
["🐆", "leopard", 2],
["🐴", "horse face", 2],
["🫎", "moose", 2],
["🫏", "donkey", 2],
["🐎", "horse", 2],
["🦄", "unicorn", 2],
["🦓", "zebra", 2],
["🦌", "deer", 2],
["🦬", "bison", 2],
["🐮", "cow face", 2],
["🐂", "ox", 2],
["🐃", "water buffalo", 2],
["🐄", "cow", 2],
["🐷", "pig face", 2],
["🐖", "pig", 2],
["🐗", "boar", 2],
["🐽", "pig nose", 2],
["🐏", "ram", 2],
["🐑", "ewe", 2],
["🐐", "goat", 2],
["🐪", "camel", 2],
["🐫", "two-hump camel", 2],
["🦙", "llama", 2],
["🦒", "giraffe", 2],
["🐘", "elephant", 2],
["🦣", "mammoth", 2],
["🦏", "rhinoceros", 2],
["🦛", "hippopotamus", 2],
["🐭", "mouse face", 2],
["🐁", "mouse", 2],
["🐀", "rat", 2],
["🐹", "hamster", 2],
["🐰", "rabbit face", 2],
["🐇", "rabbit", 2],
["🐿️", "chipmunk", 2],
["🦫", "beaver", 2],
["🦔", "hedgehog", 2],
["🦇", "bat", 2],
["🐻", "bear", 2],
["🐻‍❄️", "polar bear", 2],
["🐨", "koala", 2],
["🐼", "panda", 2],
["🦥", "sloth", 2],
["🦦", "otter", 2],
["🦨", "skunk", 2],
["🦘", "kangaroo", 2],
["🦡", "badger", 2],
["🐾", "paw prints", 2],
["🦃", "turkey", 2],
["🐔", "chicken", 2],
["🐓", "rooster", 2],
["🐣", "hatching chick", 2],
["🐤", "baby chick", 2],
["🐥", "front-facing baby chick", 2],
["🐦", "bird", 2],
["🐧", "penguin", 2],
["🕊️", "dove", 2],
["🦅", "eagle", 2],
["🦆", "duck", 2],
["🦢", "swan", 2],
["🦉", "owl", 2],
["🦤", "dodo", 2],
["🪶", "feather", 2],
["🦩", "flamingo", 2],
["🦚", "peacock", 2],
["🦜", "parrot", 2],
["🪽", "wing", 2],
["🐦‍⬛", "black bird", 2],
["🪿", "goose", 2],
["🐦‍🔥", "phoenix", 2],
["🐸", "frog", 2],
["🐊", "crocodile", 2],
["🐢", "turtle", 2],
["🦎", "lizard", 2],
["🐍", "snake", 2],
["🐲", "dragon face", 2],
["🐉", "dragon", 2],
["🦕", "sauropod", 2],
["🦖", "T-Rex", 2],
["🐳", "spouting whale", 2],
["🐋", "whale", 2],
["🐬", "dolphin", 2],
["🫍", "orca", 2],
["🦭", "seal", 2],
["🐟", "fish", 2],
["🐠", "tropical fish", 2],
["🐡", "blowfish", 2],
["🦈", "shark", 2],
["🐙", "octopus", 2],
["🐚", "spiral shell", 2],
["🪸", "coral", 2],
["🪼", "jellyfish", 2],
["🦀", "crab", 2],
["🦞", "lobster", 2],
["🦐", "shrimp", 2],
["🦑", "squid", 2],
["🦪", "oyster", 2],
["🐌", "snail", 2],
["🦋", "butterfly", 2],
["🐛", "bug", 2],
["🐜", "ant", 2],
["🐝", "honeybee", 2],
["🪲", "beetle", 2],
["🐞", "lady beetle", 2],
["🦗", "cricket", 2],
["🪳", "cockroach", 2],
["🕷️", "spider", 2],
["🕸️", "spider web", 2],
["🦂", "scorpion", 2],
["🦟", "mosquito", 2],
["🪰", "fly", 2],
["🪱", "worm", 2],
["🦠", "microbe", 2],
["💐", "bouquet", 2],
["🌸", "cherry blossom", 2],
["💮", "white flower", 2],
["🪷", "lotus", 2],
["🏵️", "rosette", 2],
["🌹", "rose", 2],
["🥀", "wilted flower", 2],
["🌺", "hibiscus", 2],
["🌻", "sunflower", 2],
["🌼", "blossom", 2],
["🌷", "tulip", 2],
["🪻", "hyacinth", 2],
["🌱", "seedling", 2],
["🪴", "potted plant", 2],
["🌲", "evergreen tree", 2],
["🌳", "deciduous tree", 2],
["🌴", "palm tree", 2],
["🌵", "cactus", 2],
["🌾", "sheaf of rice", 2],
["🌿", "herb", 2],
["☘️", "shamrock", 2],
["🍀", "four leaf clover", 2],
["🍁", "maple leaf", 2],
["🍂", "fallen leaf", 2],
["🍃", "leaf fluttering in wind", 2],
["🪹", "empty nest", 2],
["🪺", "nest with eggs", 2],
["🍄", "mushroom", 2],
["🪾", "leafless tree", 2],
["🍇", "grapes", 3],
["🍈", "melon", 3],
["🍉", "watermelon", 3],
["🍊", "tangerine", 3],
["🍋", "lemon", 3],
["🍋‍🟩", "lime", 3],
["🍌", "banana", 3],
["🍍", "pineapple", 3],
["🥭", "mango", 3],
["🍎", "red apple", 3],
["🍏", "green apple", 3],
["🍐", "pear", 3],
["🍑", "peach", 3],
["🍒", "cherries", 3],
["🍓", "strawberry", 3],
["🫐", "blueberries", 3],
["🥝", "kiwi fruit", 3],
["🍅", "tomato", 3],
["🫒", "olive", 3],
["🥥", "coconut", 3],
["🥑", "avocado", 3],
["🍆", "eggplant", 3],
["🥔", "potato", 3],
["🥕", "carrot", 3],
["🌽", "ear of corn", 3],
["🌶️", "hot pepper", 3],
["🫑", "bell pepper", 3],
["🥒", "cucumber", 3],
["🥬", "leafy green", 3],
["🥦", "broccoli", 3],
["🧄", "garlic", 3],
["🧅", "onion", 3],
["🥜", "peanuts", 3],
["🫘", "beans", 3],
["🌰", "chestnut", 3],
["🫚", "ginger root", 3],
["🫛", "pea pod", 3],
["🍄‍🟫", "brown mushroom", 3],
["🫜", "root vegetable", 3],
["🍞", "bread", 3],
["🥐", "croissant", 3],
["🥖", "baguette bread", 3],
["🫓", "flatbread", 3],
["🥨", "pretzel", 3],
["🥯", "bagel", 3],
["🥞", "pancakes", 3],
["🧇", "waffle", 3],
["🧀", "cheese wedge", 3],
["🍖", "meat on bone", 3],
["🍗", "poultry leg", 3],
["🥩", "cut of meat", 3],
["🥓", "bacon", 3],
["🍔", "hamburger", 3],
["🍟", "french fries", 3],
["🍕", "pizza", 3],
["🌭", "hot dog", 3],
["🥪", "sandwich", 3],
["🌮", "taco", 3],
["🌯", "burrito", 3],
["🫔", "tamale", 3],
["🥙", "stuffed flatbread", 3],
["🧆", "falafel", 3],
["🥚", "egg", 3],
["🍳", "cooking", 3],
["🥘", "shallow pan of food", 3],
["🍲", "pot of food", 3],
["🫕", "fondue", 3],
["🥣", "bowl with spoon", 3],
["🥗", "green salad", 3],
["🍿", "popcorn", 3],
["🧈", "butter", 3],
["🧂", "salt", 3],
["🥫", "canned food", 3],
["🍱", "bento box", 3],
["🍘", "rice cracker", 3],
["🍙", "rice ball", 3],
["🍚", "cooked rice", 3],
["🍛", "curry rice", 3],
["🍜", "steaming bowl", 3],
["🍝", "spaghetti", 3],
["🍠", "roasted sweet potato", 3],
["🍢", "oden", 3],
["🍣", "sushi", 3],
["🍤", "fried shrimp", 3],
["🍥", "fish cake with swirl", 3],
["🥮", "moon cake", 3],
["🍡", "dango", 3],
["🥟", "dumpling", 3],
["🥠", "fortune cookie", 3],
["🥡", "takeout box", 3],
["🍦", "soft ice cream", 3],
["🍧", "shaved ice", 3],
["🍨", "ice cream", 3],
["🍩", "doughnut", 3],
["🍪", "cookie", 3],
["🎂", "birthday cake", 3],
["🍰", "shortcake", 3],
["🧁", "cupcake", 3],
["🥧", "pie", 3],
["🍫", "chocolate bar", 3],
["🍬", "candy", 3],
["🍭", "lollipop", 3],
["🍮", "custard", 3],
["🍯", "honey pot", 3],
["🍼", "baby bottle", 3],
["🥛", "glass of milk", 3],
["☕", "hot beverage", 3],
["🫖", "teapot", 3],
["🍵", "teacup without handle", 3],
["🍶", "sake", 3],
["🍾", "bottle with popping cork", 3],
["🍷", "wine glass", 3],
["🍸", "cocktail glass", 3],
["🍹", "tropical drink", 3],
["🍺", "beer mug", 3],
["🍻", "clinking beer mugs", 3],
["🥂", "clinking glasses", 3],
["🥃", "tumbler glass", 3],
["🫗", "pouring liquid", 3],
["🥤", "cup with straw", 3],
["🧋", "bubble tea", 3],
["🧃", "beverage box", 3],
["🧉", "mate", 3],
["🧊", "ice", 3],
["🥢", "chopsticks", 3],
["🍽️", "fork and knife with plate", 3],
["🍴", "fork and knife", 3],
["🥄", "spoon", 3],
["🔪", "kitchen knife", 3],
["🫙", "jar", 3],
["🏺", "amphora", 3],
["🌍", "globe showing Europe-Africa", 4],
["🌎", "globe showing Americas", 4],
["🌏", "globe showing Asia-Australia", 4],
["🌐", "globe with meridians", 4],
["🗺️", "world map", 4],
["🗾", "map of Japan", 4],
["🧭", "compass", 4],
["🏔️", "snow-capped mountain", 4],
["⛰️", "mountain", 4],
["🛘", "landslide", 4],
["🌋", "volcano", 4],
["🗻", "mount fuji", 4],
["🏕️", "camping", 4],
["🏖️", "beach with umbrella", 4],
["🏜️", "desert", 4],
["🏝️", "desert island", 4],
["🏞️", "national park", 4],
["🏟️", "stadium", 4],
["🏛️", "classical building", 4],
["🏗️", "building construction", 4],
["🧱", "brick", 4],
["🪨", "rock", 4],
["🪵", "wood", 4],
["🛖", "hut", 4],
["🏘️", "houses", 4],
["🏚️", "derelict house", 4],
["🏠", "house", 4],
["🏡", "house with garden", 4],
["🏢", "office building", 4],
["🏣", "Japanese post office", 4],
["🏤", "post office", 4],
["🏥", "hospital", 4],
["🏦", "bank", 4],
["🏨", "hotel", 4],
["🏩", "love hotel", 4],
["🏪", "convenience store", 4],
["🏫", "school", 4],
["🏬", "department store", 4],
["🏭", "factory", 4],
["🏯", "Japanese castle", 4],
["🏰", "castle", 4],
["💒", "wedding", 4],
["🗼", "Tokyo tower", 4],
["🗽", "Statue of Liberty", 4],
["⛪", "church", 4],
["🕌", "mosque", 4],
["🛕", "hindu temple", 4],
["🕍", "synagogue", 4],
["⛩️", "shinto shrine", 4],
["🕋", "kaaba", 4],
["⛲", "fountain", 4],
["⛺", "tent", 4],
["🌁", "foggy", 4],
["🌃", "night with stars", 4],
["🏙️", "cityscape", 4],
["🌄", "sunrise over mountains", 4],
["🌅", "sunrise", 4],
["🌆", "cityscape at dusk", 4],
["🌇", "sunset", 4],
["🌉", "bridge at night", 4],
["♨️", "hot springs", 4],
["🎠", "carousel horse", 4],
["🛝", "playground slide", 4],
["🎡", "ferris wheel", 4],
["🎢", "roller coaster", 4],
["💈", "barber pole", 4],
["🎪", "circus tent", 4],
["🚂", "locomotive", 4],
["🚃", "railway car", 4],
["🚄", "high-speed train", 4],
["🚅", "bullet train", 4],
["🚆", "train", 4],
["🚇", "metro", 4],
["🚈", "light rail", 4],
["🚉", "station", 4],
["🚊", "tram", 4],
["🚝", "monorail", 4],
["🚞", "mountain railway", 4],
["🚋", "tram car", 4],
["🚌", "bus", 4],
["🚍", "oncoming bus", 4],
["🚎", "trolleybus", 4],
["🚐", "minibus", 4],
["🚑", "ambulance", 4],
["🚒", "fire engine", 4],
["🚓", "police car", 4],
["🚔", "oncoming police car", 4],
["🚕", "taxi", 4],
["🚖", "oncoming taxi", 4],
["🚗", "automobile", 4],
["🚘", "oncoming automobile", 4],
["🚙", "sport utility vehicle", 4],
["🛻", "pickup truck", 4],
["🚚", "delivery truck", 4],
["🚛", "articulated lorry", 4],
["🚜", "tractor", 4],
["🏎️", "racing car", 4],
["🏍️", "motorcycle", 4],
["🛵", "motor scooter", 4],
["🦽", "manual wheelchair", 4],
["🦼", "motorized wheelchair", 4],
["🛺", "auto rickshaw", 4],
["🚲", "bicycle", 4],
["🛴", "kick scooter", 4],
["🛹", "skateboard", 4],
["🛼", "roller skate", 4],
["🚏", "bus stop", 4],
["🛣️", "motorway", 4],
["🛤️", "railway track", 4],
["🛢️", "oil drum", 4],
["⛽", "fuel pump", 4],
["🛞", "wheel", 4],
["🚨", "police car light", 4],
["🚥", "horizontal traffic light", 4],
["🚦", "vertical traffic light", 4],
["🛑", "stop sign", 4],
["🚧", "construction", 4],
["⚓", "anchor", 4],
["🛟", "ring buoy", 4],
["⛵", "sailboat", 4],
["🛶", "canoe", 4],
["🚤", "speedboat", 4],
["🛳️", "passenger ship", 4],
["⛴️", "ferry", 4],
["🛥️", "motor boat", 4],
["🚢", "ship", 4],
["✈️", "airplane", 4],
["🛩️", "small airplane", 4],
["🛫", "airplane departure", 4],
["🛬", "airplane arrival", 4],
["🪂", "parachute", 4],
["💺", "seat", 4],
["🚁", "helicopter", 4],
["🚟", "suspension railway", 4],
["🚠", "mountain cableway", 4],
["🚡", "aerial tramway", 4],
["🛰️", "satellite", 4],
["🚀", "rocket", 4],
["🛸", "flying saucer", 4],
["🛎️", "bellhop bell", 4],
["🧳", "luggage", 4],
["⌛", "hourglass done", 4],
["⏳", "hourglass not done", 4],
["⌚", "watch", 4],
["⏰", "alarm clock", 4],
["⏱️", "stopwatch", 4],
["⏲️", "timer clock", 4],
["🕰️", "mantelpiece clock", 4],
["🕛", "twelve o’clock", 4],
["🕧", "twelve-thirty", 4],
["🕐", "one o’clock", 4],
["🕜", "one-thirty", 4],
["🕑", "two o’clock", 4],
["🕝", "two-thirty", 4],
["🕒", "three o’clock", 4],
["🕞", "three-thirty", 4],
["🕓", "four o’clock", 4],
["🕟", "four-thirty", 4],
["🕔", "five o’clock", 4],
["🕠", "five-thirty", 4],
["🕕", "six o’clock", 4],
["🕡", "six-thirty", 4],
["🕖", "seven o’clock", 4],
["🕢", "seven-thirty", 4],
["🕗", "eight o’clock", 4],
["🕣", "eight-thirty", 4],
["🕘", "nine o’clock", 4],
["🕤", "nine-thirty", 4],
["🕙", "ten o’clock", 4],
["🕥", "ten-thirty", 4],
["🕚", "eleven o’clock", 4],
["🕦", "eleven-thirty", 4],
["🌑", "new moon", 4],
["🌒", "waxing crescent moon", 4],
["🌓", "first quarter moon", 4],
["🌔", "waxing gibbous moon", 4],
["🌕", "full moon", 4],
["🌖", "waning gibbous moon", 4],
["🌗", "last quarter moon", 4],
["🌘", "waning crescent moon", 4],
["🌙", "crescent moon", 4],
["🌚", "new moon face", 4],
["🌛", "first quarter moon face", 4],
["🌜", "last quarter moon face", 4],
["🌡️", "thermometer", 4],
["☀️", "sun", 4],
["🌝", "full moon face", 4],
["🌞", "sun with face", 4],
["🪐", "ringed planet", 4],
["⭐", "star", 4],
["🌟", "glowing star", 4],
["🌠", "shooting star", 4],
["🌌", "milky way", 4],
["☁️", "cloud", 4],
["⛅", "sun behind cloud", 4],
["⛈️", "cloud with lightning and rain", 4],
["🌤️", "sun behind small cloud", 4],
["🌥️", "sun behind large cloud", 4],
["🌦️", "sun behind rain cloud", 4],
["🌧️", "cloud with rain", 4],
["🌨️", "cloud with snow", 4],
["🌩️", "cloud with lightning", 4],
["🌪️", "tornado", 4],
["🌫️", "fog", 4],
["🌬️", "wind face", 4],
["🌀", "cyclone", 4],
["🌈", "rainbow", 4],
["🌂", "closed umbrella", 4],
["☂️", "umbrella", 4],
["☔", "umbrella with rain drops", 4],
["⛱️", "umbrella on ground", 4],
["⚡", "high voltage", 4],
["❄️", "snowflake", 4],
["☃️", "snowman", 4],
["⛄", "snowman without snow", 4],
["☄️", "comet", 4],
["🔥", "fire", 4],
["💧", "droplet", 4],
["🌊", "water wave", 4],
["🎃", "jack-o-lantern", 5],
["🎄", "Christmas tree", 5],
["🎆", "fireworks", 5],
["🎇", "sparkler", 5],
["🧨", "firecracker", 5],
["✨", "sparkles", 5],
["🎈", "balloon", 5],
["🎉", "party popper", 5],
["🎊", "confetti ball", 5],
["🎋", "tanabata tree", 5],
["🎍", "pine decoration", 5],
["🎎", "Japanese dolls", 5],
["🎏", "carp streamer", 5],
["🎐", "wind chime", 5],
["🎑", "moon viewing ceremony", 5],
["🧧", "red envelope", 5],
["🎀", "ribbon", 5],
["🎁", "wrapped gift", 5],
["🎗️", "reminder ribbon", 5],
["🎟️", "admission tickets", 5],
["🎫", "ticket", 5],
["🎖️", "military medal", 5],
["🏆", "trophy", 5],
["🏅", "sports medal", 5],
["🥇", "1st place medal", 5],
["🥈", "2nd place medal", 5],
["🥉", "3rd place medal", 5],
["⚽", "soccer ball", 5],
["⚾", "baseball", 5],
["🥎", "softball", 5],
["🏀", "basketball", 5],
["🏐", "volleyball", 5],
["🏈", "american football", 5],
["🏉", "rugby football", 5],
["🎾", "tennis", 5],
["🥏", "flying disc", 5],
["🎳", "bowling", 5],
["🏏", "cricket game", 5],
["🏑", "field hockey", 5],
["🏒", "ice hockey", 5],
["🥍", "lacrosse", 5],
["🏓", "ping pong", 5],
["🏸", "badminton", 5],
["🥊", "boxing glove", 5],
["🥋", "martial arts uniform", 5],
["🥅", "goal net", 5],
["⛳", "flag in hole", 5],
["⛸️", "ice skate", 5],
["🎣", "fishing pole", 5],
["🤿", "diving mask", 5],
["🎽", "running shirt", 5],
["🎿", "skis", 5],
["🛷", "sled", 5],
["🥌", "curling stone", 5],
["🎯", "bullseye", 5],
["🪀", "yo-yo", 5],
["🪁", "kite", 5],
["🔫", "water pistol", 5],
["🎱", "pool 8 ball", 5],
["🔮", "crystal ball", 5],
["🪄", "magic wand", 5],
["🎮", "video game", 5],
["🕹️", "joystick", 5],
["🎰", "slot machine", 5],
["🎲", "game die", 5],
["🧩", "puzzle piece", 5],
["🧸", "teddy bear", 5],
["🪅", "piñata", 5],
["🪩", "mirror ball", 5],
["🪆", "nesting dolls", 5],
["♠️", "spade suit", 5],
["♥️", "heart suit", 5],
["♦️", "diamond suit", 5],
["♣️", "club suit", 5],
["♟️", "chess pawn", 5],
["🃏", "joker", 5],
["🀄", "mahjong red dragon", 5],
["🎴", "flower playing cards", 5],
["🎭", "performing arts", 5],
["🖼️", "framed picture", 5],
["🎨", "artist palette", 5],
["🧵", "thread", 5],
["🪡", "sewing needle", 5],
["🧶", "yarn", 5],
["🪢", "knot", 5],
["👓", "glasses", 6],
["🕶️", "sunglasses", 6],
["🥽", "goggles", 6],
["🥼", "lab coat", 6],
["🦺", "safety vest", 6],
["👔", "necktie", 6],
["👕", "t-shirt", 6],
["👖", "jeans", 6],
["🧣", "scarf", 6],
["🧤", "gloves", 6],
["🧥", "coat", 6],
["🧦", "socks", 6],
["👗", "dress", 6],
["👘", "kimono", 6],
["🥻", "sari", 6],
["🩱", "one-piece swimsuit", 6],
["🩲", "briefs", 6],
["🩳", "shorts", 6],
["👙", "bikini", 6],
["👚", "woman’s clothes", 6],
["🪭", "folding hand fan", 6],
["👛", "purse", 6],
["👜", "handbag", 6],
["👝", "clutch bag", 6],
["🛍️", "shopping bags", 6],
["🎒", "backpack", 6],
["🩴", "thong sandal", 6],
["👞", "man’s shoe", 6],
["👟", "running shoe", 6],
["🥾", "hiking boot", 6],
["🥿", "flat shoe", 6],
["👠", "high-heeled shoe", 6],
["👡", "woman’s sandal", 6],
["🩰", "ballet shoes", 6],
["👢", "woman’s boot", 6],
["🪮", "hair pick", 6],
["👑", "crown", 6],
["👒", "woman’s hat", 6],
["🎩", "top hat", 6],
["🎓", "graduation cap", 6],
["🧢", "billed cap", 6],
["🪖", "military helmet", 6],
["⛑️", "rescue worker’s helmet", 6],
["📿", "prayer beads", 6],
["💄", "lipstick", 6],
["💍", "ring", 6],
["💎", "gem stone", 6],
["🔇", "muted speaker", 6],
["🔈", "speaker low volume", 6],
["🔉", "speaker medium volume", 6],
["🔊", "speaker high volume", 6],
["📢", "loudspeaker", 6],
["📣", "megaphone", 6],
["📯", "postal horn", 6],
["🔔", "bell", 6],
["🔕", "bell with slash", 6],
["🎼", "musical score", 6],
["🎵", "musical note", 6],
["🎶", "musical notes", 6],
["🎙️", "studio microphone", 6],
["🎚️", "level slider", 6],
["🎛️", "control knobs", 6],
["🎤", "microphone", 6],
["🎧", "headphone", 6],
["📻", "radio", 6],
["🎷", "saxophone", 6],
["🎺", "trumpet", 6],
["🪊", "trombone", 6],
["🪗", "accordion", 6],
["🎸", "guitar", 6],
["🎹", "musical keyboard", 6],
["🎻", "violin", 6],
["🪕", "banjo", 6],
["🥁", "drum", 6],
["🪘", "long drum", 6],
["🪇", "maracas", 6],
["🪈", "flute", 6],
["🪉", "harp", 6],
["📱", "mobile phone", 6],
["📲", "mobile phone with arrow", 6],
["☎️", "telephone", 6],
["📞", "telephone receiver", 6],
["📟", "pager", 6],
["📠", "fax machine", 6],
["🔋", "battery", 6],
["🪫", "low battery", 6],
["🔌", "electric plug", 6],
["💻", "laptop", 6],
["🖥️", "desktop computer", 6],
["🖨️", "printer", 6],
["⌨️", "keyboard", 6],
["🖱️", "computer mouse", 6],
["🖲️", "trackball", 6],
["💽", "computer disk", 6],
["💾", "floppy disk", 6],
["💿", "optical disk", 6],
["📀", "dvd", 6],
["🧮", "abacus", 6],
["🎥", "movie camera", 6],
["🎞️", "film frames", 6],
["📽️", "film projector", 6],
["🎬", "clapper board", 6],
["📺", "television", 6],
["📷", "camera", 6],
["📸", "camera with flash", 6],
["📹", "video camera", 6],
["📼", "videocassette", 6],
["🔍", "magnifying glass tilted left", 6],
["🔎", "magnifying glass tilted right", 6],
["🕯️", "candle", 6],
["💡", "light bulb", 6],
["🔦", "flashlight", 6],
["🏮", "red paper lantern", 6],
["🪔", "diya lamp", 6],
["📔", "notebook with decorative cover", 6],
["📕", "closed book", 6],
["📖", "open book", 6],
["📗", "green book", 6],
["📘", "blue book", 6],
["📙", "orange book", 6],
["📚", "books", 6],
["📓", "notebook", 6],
["📒", "ledger", 6],
["📃", "page with curl", 6],
["📜", "scroll", 6],
["📄", "page facing up", 6],
["📰", "newspaper", 6],
["🗞️", "rolled-up newspaper", 6],
["📑", "bookmark tabs", 6],
["🔖", "bookmark", 6],
["🏷️", "label", 6],
["🪙", "coin", 6],
["💰", "money bag", 6],
["🪎", "treasure chest", 6],
["💴", "yen banknote", 6],
["💵", "dollar banknote", 6],
["💶", "euro banknote", 6],
["💷", "pound banknote", 6],
["💸", "money with wings", 6],
["💳", "credit card", 6],
["🧾", "receipt", 6],
["💹", "chart increasing with yen", 6],
["✉️", "envelope", 6],
["📧", "e-mail", 6],
["📨", "incoming envelope", 6],
["📩", "envelope with arrow", 6],
["📤", "outbox tray", 6],
["📥", "inbox tray", 6],
["📦", "package", 6],
["📫", "closed mailbox with raised flag", 6],
["📪", "closed mailbox with lowered flag", 6],
["📬", "open mailbox with raised flag", 6],
["📭", "open mailbox with lowered flag", 6],
["📮", "postbox", 6],
["🗳️", "ballot box with ballot", 6],
["✏️", "pencil", 6],
["✒️", "black nib", 6],
["🖋️", "fountain pen", 6],
["🖊️", "pen", 6],
["🖌️", "paintbrush", 6],
["🖍️", "crayon", 6],
["📝", "memo", 6],
["💼", "briefcase", 6],
["📁", "file folder", 6],
["📂", "open file folder", 6],
["🗂️", "card index dividers", 6],
["📅", "calendar", 6],
["📆", "tear-off calendar", 6],
["🗒️", "spiral notepad", 6],
["🗓️", "spiral calendar", 6],
["📇", "card index", 6],
["📈", "chart increasing", 6],
["📉", "chart decreasing", 6],
["📊", "bar chart", 6],
["📋", "clipboard", 6],
["📌", "pushpin", 6],
["📍", "round pushpin", 6],
["📎", "paperclip", 6],
["🖇️", "linked paperclips", 6],
["📏", "straight ruler", 6],
["📐", "triangular ruler", 6],
["✂️", "scissors", 6],
["🗃️", "card file box", 6],
["🗄️", "file cabinet", 6],
["🗑️", "wastebasket", 6],
["🔒", "locked", 6],
["🔓", "unlocked", 6],
["🔏", "locked with pen", 6],
["🔐", "locked with key", 6],
["🔑", "key", 6],
["🗝️", "old key", 6],
["🔨", "hammer", 6],
["🪓", "axe", 6],
["⛏️", "pick", 6],
["⚒️", "hammer and pick", 6],
["🛠️", "hammer and wrench", 6],
["🗡️", "dagger", 6],
["⚔️", "crossed swords", 6],
["💣", "bomb", 6],
["🪃", "boomerang", 6],
["🏹", "bow and arrow", 6],
["🛡️", "shield", 6],
["🪚", "carpentry saw", 6],
["🔧", "wrench", 6],
["🪛", "screwdriver", 6],
["🔩", "nut and bolt", 6],
["⚙️", "gear", 6],
["🗜️", "clamp", 6],
["⚖️", "balance scale", 6],
["🦯", "white cane", 6],
["🔗", "link", 6],
["⛓️‍💥", "broken chain", 6],
["⛓️", "chains", 6],
["🪝", "hook", 6],
["🧰", "toolbox", 6],
["🧲", "magnet", 6],
["🪜", "ladder", 6],
["🪏", "shovel", 6],
["⚗️", "alembic", 6],
["🧪", "test tube", 6],
["🧫", "petri dish", 6],
["🧬", "dna", 6],
["🔬", "microscope", 6],
["🔭", "telescope", 6],
["📡", "satellite antenna", 6],
["💉", "syringe", 6],
["🩸", "drop of blood", 6],
["💊", "pill", 6],
["🩹", "adhesive bandage", 6],
["🩼", "crutch", 6],
["🩺", "stethoscope", 6],
["🩻", "x-ray", 6],
["🚪", "door", 6],
["🛗", "elevator", 6],
["🪞", "mirror", 6],
["🪟", "window", 6],
["🛏️", "bed", 6],
["🛋️", "couch and lamp", 6],
["🪑", "chair", 6],
["🚽", "toilet", 6],
["🪠", "plunger", 6],
["🚿", "shower", 6],
["🛁", "bathtub", 6],
["🪤", "mouse trap", 6],
["🪒", "razor", 6],
["🧴", "lotion bottle", 6],
["🧷", "safety pin", 6],
["🧹", "broom", 6],
["🧺", "basket", 6],
["🧻", "roll of paper", 6],
["🪣", "bucket", 6],
["🧼", "soap", 6],
["🫧", "bubbles", 6],
["🪥", "toothbrush", 6],
["🧽", "sponge", 6],
["🧯", "fire extinguisher", 6],
["🛒", "shopping cart", 6],
["🚬", "cigarette", 6],
["⚰️", "coffin", 6],
["🪦", "headstone", 6],
["⚱️", "funeral urn", 6],
["🧿", "nazar amulet", 6],
["🪬", "hamsa", 6],
["🗿", "moai", 6],
["🪧", "placard", 6],
["🪪", "identification card", 6],
["🏧", "ATM sign", 7],
["🚮", "litter in bin sign", 7],
["🚰", "potable water", 7],
["♿", "wheelchair symbol", 7],
["🚹", "men’s room", 7],
["🚺", "women’s room", 7],
["🚻", "restroom", 7],
["🚼", "baby symbol", 7],
["🚾", "water closet", 7],
["🛂", "passport control", 7],
["🛃", "customs", 7],
["🛄", "baggage claim", 7],
["🛅", "left luggage", 7],
["⚠️", "warning", 7],
["🚸", "children crossing", 7],
["⛔", "no entry", 7],
["🚫", "prohibited", 7],
["🚳", "no bicycles", 7],
["🚭", "no smoking", 7],
["🚯", "no littering", 7],
["🚱", "non-potable water", 7],
["🚷", "no pedestrians", 7],
["📵", "no mobile phones", 7],
["🔞", "no one under eighteen", 7],
["☢️", "radioactive", 7],
["☣️", "biohazard", 7],
["⬆️", "up arrow", 7],
["↗️", "up-right arrow", 7],
["➡️", "right arrow", 7],
["↘️", "down-right arrow", 7],
["⬇️", "down arrow", 7],
["↙️", "down-left arrow", 7],
["⬅️", "left arrow", 7],
["↖️", "up-left arrow", 7],
["↕️", "up-down arrow", 7],
["↔️", "left-right arrow", 7],
["↩️", "right arrow curving left", 7],
["↪️", "left arrow curving right", 7],
["⤴️", "right arrow curving up", 7],
["⤵️", "right arrow curving down", 7],
["🔃", "clockwise vertical arrows", 7],
["🔄", "counterclockwise arrows button", 7],
["🔙", "BACK arrow", 7],
["🔚", "END arrow", 7],
["🔛", "ON! arrow", 7],
["🔜", "SOON arrow", 7],
["🔝", "TOP arrow", 7],
["🛐", "place of worship", 7],
["⚛️", "atom symbol", 7],
["🕉️", "om", 7],
["✡️", "star of David", 7],
["☸️", "wheel of dharma", 7],
["☯️", "yin yang", 7],
["✝️", "latin cross", 7],
["☦️", "orthodox cross", 7],
["☪️", "star and crescent", 7],
["☮️", "peace symbol", 7],
["🕎", "menorah", 7],
["🔯", "dotted six-pointed star", 7],
["🪯", "khanda", 7],
["♈", "Aries", 7],
["♉", "Taurus", 7],
["♊", "Gemini", 7],
["♋", "Cancer", 7],
["♌", "Leo", 7],
["♍", "Virgo", 7],
["♎", "Libra", 7],
["♏", "Scorpio", 7],
["♐", "Sagittarius", 7],
["♑", "Capricorn", 7],
["♒", "Aquarius", 7],
["♓", "Pisces", 7],
["⛎", "Ophiuchus", 7],
["🔀", "shuffle tracks button", 7],
["🔁", "repeat button", 7],
["🔂", "repeat single button", 7],
["▶️", "play button", 7],
["⏩", "fast-forward button", 7],
["⏭️", "next track button", 7],
["⏯️", "play or pause button", 7],
["◀️", "reverse button", 7],
["⏪", "fast reverse button", 7],
["⏮️", "last track button", 7],
["🔼", "upwards button", 7],
["⏫", "fast up button", 7],
["🔽", "downwards button", 7],
["⏬", "fast down button", 7],
["⏸️", "pause button", 7],
["⏹️", "stop button", 7],
["⏺️", "record button", 7],
["⏏️", "eject button", 7],
["🎦", "cinema", 7],
["🔅", "dim button", 7],
["🔆", "bright button", 7],
["📶", "antenna bars", 7],
["🛜", "wireless", 7],
["📳", "vibration mode", 7],
["📴", "mobile phone off", 7],
["♀️", "female sign", 7],
["♂️", "male sign", 7],
["⚧️", "transgender symbol", 7],
["✖️", "multiply", 7],
["➕", "plus", 7],
["➖", "minus", 7],
["➗", "divide", 7],
["🟰", "heavy equals sign", 7],
["♾️", "infinity", 7],
["‼️", "double exclamation mark", 7],
["⁉️", "exclamation question mark", 7],
["❓", "red question mark", 7],
["❔", "white question mark", 7],
["❕", "white exclamation mark", 7],
["❗", "red exclamation mark", 7],
["〰️", "wavy dash", 7],
["💱", "currency exchange", 7],
["💲", "heavy dollar sign", 7],
["⚕️", "medical symbol", 7],
["♻️", "recycling symbol", 7],
["⚜️", "fleur-de-lis", 7],
["🔱", "trident emblem", 7],
["📛", "name badge", 7],
["🔰", "Japanese symbol for beginner", 7],
["⭕", "hollow red circle", 7],
["✅", "check mark button", 7],
["☑️", "check box with check", 7],
["✔️", "check mark", 7],
["❌", "cross mark", 7],
["❎", "cross mark button", 7],
["➰", "curly loop", 7],
["➿", "double curly loop", 7],
["〽️", "part alternation mark", 7],
["✳️", "eight-spoked asterisk", 7],
["✴️", "eight-pointed star", 7],
["❇️", "sparkle", 7],
["©️", "copyright", 7],
["®️", "registered", 7],
["™️", "trade mark", 7],
["🫟", "splatter", 7],
["#️⃣", "keycap: #", 7],
["*️⃣", "keycap: *", 7],
["0️⃣", "keycap: 0", 7],
["1️⃣", "keycap: 1", 7],
["2️⃣", "keycap: 2", 7],
["3️⃣", "keycap: 3", 7],
["4️⃣", "keycap: 4", 7],
["5️⃣", "keycap: 5", 7],
["6️⃣", "keycap: 6", 7],
["7️⃣", "keycap: 7", 7],
["8️⃣", "keycap: 8", 7],
["9️⃣", "keycap: 9", 7],
["🔟", "keycap: 10", 7],
["🔠", "input latin uppercase", 7],
["🔡", "input latin lowercase", 7],
["🔢", "input numbers", 7],
["🔣", "input symbols", 7],
["🔤", "input latin letters", 7],
["🅰️", "A button (blood type)", 7],
["🆎", "AB button (blood type)", 7],
["🅱️", "B button (blood type)", 7],
["🆑", "CL button", 7],
["🆒", "COOL button", 7],
["🆓", "FREE button", 7],
["ℹ️", "information", 7],
["🆔", "ID button", 7],
["Ⓜ️", "circled M", 7],
["🆕", "NEW button", 7],
["🆖", "NG button", 7],
["🅾️", "O button (blood type)", 7],
["🆗", "OK button", 7],
["🅿️", "P button", 7],
["🆘", "SOS button", 7],
["🆙", "UP! button", 7],
["🆚", "VS button", 7],
["🈁", "Japanese “here” button", 7],
["🈂️", "Japanese “service charge” button", 7],
["🈷️", "Japanese “monthly amount” button", 7],
["🈶", "Japanese “not free of charge” button", 7],
["🈯", "Japanese “reserved” button", 7],
["🉐", "Japanese “bargain” button", 7],
["🈹", "Japanese “discount” button", 7],
["🈚", "Japanese “free of charge” button", 7],
["🈲", "Japanese “prohibited” button", 7],
["🉑", "Japanese “acceptable” button", 7],
["🈸", "Japanese “application” button", 7],
["🈴", "Japanese “passing grade” button", 7],
["🈳", "Japanese “vacancy” button", 7],
["㊗️", "Japanese “congratulations” button", 7],
["㊙️", "Japanese “secret” button", 7],
["🈺", "Japanese “open for business” button", 7],
["🈵", "Japanese “no vacancy” button", 7],
["🔴", "red circle", 7],
["🟠", "orange circle", 7],
["🟡", "yellow circle", 7],
["🟢", "green circle", 7],
["🔵", "blue circle", 7],
["🟣", "purple circle", 7],
["🟤", "brown circle", 7],
["⚫", "black circle", 7],
["⚪", "white circle", 7],
["🟥", "red square", 7],
["🟧", "orange square", 7],
["🟨", "yellow square", 7],
["🟩", "green square", 7],
["🟦", "blue square", 7],
["🟪", "purple square", 7],
["🟫", "brown square", 7],
["⬛", "black large square", 7],
["⬜", "white large square", 7],
["◼️", "black medium square", 7],
["◻️", "white medium square", 7],
["◾", "black medium-small square", 7],
["◽", "white medium-small square", 7],
["▪️", "black small square", 7],
["▫️", "white small square", 7],
["🔶", "large orange diamond", 7],
["🔷", "large blue diamond", 7],
["🔸", "small orange diamond", 7],
["🔹", "small blue diamond", 7],
["🔺", "red triangle pointed up", 7],
["🔻", "red triangle pointed down", 7],
["💠", "diamond with a dot", 7],
["🔘", "radio button", 7],
["🔳", "white square button", 7],
["🔲", "black square button", 7],
["🏁", "chequered flag", 8],
["🚩", "triangular flag", 8],
["🎌", "crossed flags", 8],
["🏴", "black flag", 8],
["🏳️", "white flag", 8],
["🏳️‍🌈", "rainbow flag", 8],
["🏳️‍⚧️", "transgender flag", 8],
["🏴‍☠️", "pirate flag", 8],
["🇦🇨", "flag: Ascension Island", 8],
["🇦🇩", "flag: Andorra", 8],
["🇦🇪", "flag: United Arab Emirates", 8],
["🇦🇫", "flag: Afghanistan", 8],
["🇦🇬", "flag: Antigua & Barbuda", 8],
["🇦🇮", "flag: Anguilla", 8],
["🇦🇱", "flag: Albania", 8],
["🇦🇲", "flag: Armenia", 8],
["🇦🇴", "flag: Angola", 8],
["🇦🇶", "flag: Antarctica", 8],
["🇦🇷", "flag: Argentina", 8],
["🇦🇸", "flag: American Samoa", 8],
["🇦🇹", "flag: Austria", 8],
["🇦🇺", "flag: Australia", 8],
["🇦🇼", "flag: Aruba", 8],
["🇦🇽", "flag: Åland Islands", 8],
["🇦🇿", "flag: Azerbaijan", 8],
["🇧🇦", "flag: Bosnia & Herzegovina", 8],
["🇧🇧", "flag: Barbados", 8],
["🇧🇩", "flag: Bangladesh", 8],
["🇧🇪", "flag: Belgium", 8],
["🇧🇫", "flag: Burkina Faso", 8],
["🇧🇬", "flag: Bulgaria", 8],
["🇧🇭", "flag: Bahrain", 8],
["🇧🇮", "flag: Burundi", 8],
["🇧🇯", "flag: Benin", 8],
["🇧🇱", "flag: St. Barthélemy", 8],
["🇧🇲", "flag: Bermuda", 8],
["🇧🇳", "flag: Brunei", 8],
["🇧🇴", "flag: Bolivia", 8],
["🇧🇶", "flag: Caribbean Netherlands", 8],
["🇧🇷", "flag: Brazil", 8],
["🇧🇸", "flag: Bahamas", 8],
["🇧🇹", "flag: Bhutan", 8],
["🇧🇻", "flag: Bouvet Island", 8],
["🇧🇼", "flag: Botswana", 8],
["🇧🇾", "flag: Belarus", 8],
["🇧🇿", "flag: Belize", 8],
["🇨🇦", "flag: Canada", 8],
["🇨🇨", "flag: Cocos (Keeling) Islands", 8],
["🇨🇩", "flag: Congo - Kinshasa", 8],
["🇨🇫", "flag: Central African Republic", 8],
["🇨🇬", "flag: Congo - Brazzaville", 8],
["🇨🇭", "flag: Switzerland", 8],
["🇨🇮", "flag: Côte d’Ivoire", 8],
["🇨🇰", "flag: Cook Islands", 8],
["🇨🇱", "flag: Chile", 8],
["🇨🇲", "flag: Cameroon", 8],
["🇨🇳", "flag: China", 8],
["🇨🇴", "flag: Colombia", 8],
["🇨🇵", "flag: Clipperton Island", 8],
["🇨🇶", "flag: Sark", 8],
["🇨🇷", "flag: Costa Rica", 8],
["🇨🇺", "flag: Cuba", 8],
["🇨🇻", "flag: Cape Verde", 8],
["🇨🇼", "flag: Curaçao", 8],
["🇨🇽", "flag: Christmas Island", 8],
["🇨🇾", "flag: Cyprus", 8],
["🇨🇿", "flag: Czechia", 8],
["🇩🇪", "flag: Germany", 8],
["🇩🇬", "flag: Diego Garcia", 8],
["🇩🇯", "flag: Djibouti", 8],
["🇩🇰", "flag: Denmark", 8],
["🇩🇲", "flag: Dominica", 8],
["🇩🇴", "flag: Dominican Republic", 8],
["🇩🇿", "flag: Algeria", 8],
["🇪🇦", "flag: Ceuta & Melilla", 8],
["🇪🇨", "flag: Ecuador", 8],
["🇪🇪", "flag: Estonia", 8],
["🇪🇬", "flag: Egypt", 8],
["🇪🇭", "flag: Western Sahara", 8],
["🇪🇷", "flag: Eritrea", 8],
["🇪🇸", "flag: Spain", 8],
["🇪🇹", "flag: Ethiopia", 8],
["🇪🇺", "flag: European Union", 8],
["🇫🇮", "flag: Finland", 8],
["🇫🇯", "flag: Fiji", 8],
["🇫🇰", "flag: Falkland Islands", 8],
["🇫🇲", "flag: Micronesia", 8],
["🇫🇴", "flag: Faroe Islands", 8],
["🇫🇷", "flag: France", 8],
["🇬🇦", "flag: Gabon", 8],
["🇬🇧", "flag: United Kingdom", 8],
["🇬🇩", "flag: Grenada", 8],
["🇬🇪", "flag: Georgia", 8],
["🇬🇫", "flag: French Guiana", 8],
["🇬🇬", "flag: Guernsey", 8],
["🇬🇭", "flag: Ghana", 8],
["🇬🇮", "flag: Gibraltar", 8],
["🇬🇱", "flag: Greenland", 8],
["🇬🇲", "flag: Gambia", 8],
["🇬🇳", "flag: Guinea", 8],
["🇬🇵", "flag: Guadeloupe", 8],
["🇬🇶", "flag: Equatorial Guinea", 8],
["🇬🇷", "flag: Greece", 8],
["🇬🇸", "flag: South Georgia & South Sandwich Islands", 8],
["🇬🇹", "flag: Guatemala", 8],
["🇬🇺", "flag: Guam", 8],
["🇬🇼", "flag: Guinea-Bissau", 8],
["🇬🇾", "flag: Guyana", 8],
["🇭🇰", "flag: Hong Kong SAR China", 8],
["🇭🇲", "flag: Heard & McDonald Islands", 8],
["🇭🇳", "flag: Honduras", 8],
["🇭🇷", "flag: Croatia", 8],
["🇭🇹", "flag: Haiti", 8],
["🇭🇺", "flag: Hungary", 8],
["🇮🇨", "flag: Canary Islands", 8],
["🇮🇩", "flag: Indonesia", 8],
["🇮🇪", "flag: Ireland", 8],
["🇮🇱", "flag: Israel", 8],
["🇮🇲", "flag: Isle of Man", 8],
["🇮🇳", "flag: India", 8],
["🇮🇴", "flag: British Indian Ocean Territory", 8],
["🇮🇶", "flag: Iraq", 8],
["🇮🇷", "flag: Iran", 8],
["🇮🇸", "flag: Iceland", 8],
["🇮🇹", "flag: Italy", 8],
["🇯🇪", "flag: Jersey", 8],
["🇯🇲", "flag: Jamaica", 8],
["🇯🇴", "flag: Jordan", 8],
["🇯🇵", "flag: Japan", 8],
["🇰🇪", "flag: Kenya", 8],
["🇰🇬", "flag: Kyrgyzstan", 8],
["🇰🇭", "flag: Cambodia", 8],
["🇰🇮", "flag: Kiribati", 8],
["🇰🇲", "flag: Comoros", 8],
["🇰🇳", "flag: St. Kitts & Nevis", 8],
["🇰🇵", "flag: North Korea", 8],
["🇰🇷", "flag: South Korea", 8],
["🇰🇼", "flag: Kuwait", 8],
["🇰🇾", "flag: Cayman Islands", 8],
["🇰🇿", "flag: Kazakhstan", 8],
["🇱🇦", "flag: Laos", 8],
["🇱🇧", "flag: Lebanon", 8],
["🇱🇨", "flag: St. Lucia", 8],
["🇱🇮", "flag: Liechtenstein", 8],
["🇱🇰", "flag: Sri Lanka", 8],
["🇱🇷", "flag: Liberia", 8],
["🇱🇸", "flag: Lesotho", 8],
["🇱🇹", "flag: Lithuania", 8],
["🇱🇺", "flag: Luxembourg", 8],
["🇱🇻", "flag: Latvia", 8],
["🇱🇾", "flag: Libya", 8],
["🇲🇦", "flag: Morocco", 8],
["🇲🇨", "flag: Monaco", 8],
["🇲🇩", "flag: Moldova", 8],
["🇲🇪", "flag: Montenegro", 8],
["🇲🇫", "flag: St. Martin", 8],
["🇲🇬", "flag: Madagascar", 8],
["🇲🇭", "flag: Marshall Islands", 8],
["🇲🇰", "flag: North Macedonia", 8],
["🇲🇱", "flag: Mali", 8],
["🇲🇲", "flag: Myanmar (Burma)", 8],
["🇲🇳", "flag: Mongolia", 8],
["🇲🇴", "flag: Macao SAR China", 8],
["🇲🇵", "flag: Northern Mariana Islands", 8],
["🇲🇶", "flag: Martinique", 8],
["🇲🇷", "flag: Mauritania", 8],
["🇲🇸", "flag: Montserrat", 8],
["🇲🇹", "flag: Malta", 8],
["🇲🇺", "flag: Mauritius", 8],
["🇲🇻", "flag: Maldives", 8],
["🇲🇼", "flag: Malawi", 8],
["🇲🇽", "flag: Mexico", 8],
["🇲🇾", "flag: Malaysia", 8],
["🇲🇿", "flag: Mozambique", 8],
["🇳🇦", "flag: Namibia", 8],
["🇳🇨", "flag: New Caledonia", 8],
["🇳🇪", "flag: Niger", 8],
["🇳🇫", "flag: Norfolk Island", 8],
["🇳🇬", "flag: Nigeria", 8],
["🇳🇮", "flag: Nicaragua", 8],
["🇳🇱", "flag: Netherlands", 8],
["🇳🇴", "flag: Norway", 8],
["🇳🇵", "flag: Nepal", 8],
["🇳🇷", "flag: Nauru", 8],
["🇳🇺", "flag: Niue", 8],
["🇳🇿", "flag: New Zealand", 8],
["🇴🇲", "flag: Oman", 8],
["🇵🇦", "flag: Panama", 8],
["🇵🇪", "flag: Peru", 8],
["🇵🇫", "flag: French Polynesia", 8],
["🇵🇬", "flag: Papua New Guinea", 8],
["🇵🇭", "flag: Philippines", 8],
["🇵🇰", "flag: Pakistan", 8],
["🇵🇱", "flag: Poland", 8],
["🇵🇲", "flag: St. Pierre & Miquelon", 8],
["🇵🇳", "flag: Pitcairn Islands", 8],
["🇵🇷", "flag: Puerto Rico", 8],
["🇵🇸", "flag: Palestinian Territories", 8],
["🇵🇹", "flag: Portugal", 8],
["🇵🇼", "flag: Palau", 8],
["🇵🇾", "flag: Paraguay", 8],
["🇶🇦", "flag: Qatar", 8],
["🇷🇪", "flag: Réunion", 8],
["🇷🇴", "flag: Romania", 8],
["🇷🇸", "flag: Serbia", 8],
["🇷🇺", "flag: Russia", 8],
["🇷🇼", "flag: Rwanda", 8],
["🇸🇦", "flag: Saudi Arabia", 8],
["🇸🇧", "flag: Solomon Islands", 8],
["🇸🇨", "flag: Seychelles", 8],
["🇸🇩", "flag: Sudan", 8],
["🇸🇪", "flag: Sweden", 8],
["🇸🇬", "flag: Singapore", 8],
["🇸🇭", "flag: St. Helena", 8],
["🇸🇮", "flag: Slovenia", 8],
["🇸🇯", "flag: Svalbard & Jan Mayen", 8],
["🇸🇰", "flag: Slovakia", 8],
["🇸🇱", "flag: Sierra Leone", 8],
["🇸🇲", "flag: San Marino", 8],
["🇸🇳", "flag: Senegal", 8],
["🇸🇴", "flag: Somalia", 8],
["🇸🇷", "flag: Suriname", 8],
["🇸🇸", "flag: South Sudan", 8],
["🇸🇹", "flag: São Tomé & Príncipe", 8],
["🇸🇻", "flag: El Salvador", 8],
["🇸🇽", "flag: Sint Maarten", 8],
["🇸🇾", "flag: Syria", 8],
["🇸🇿", "flag: Eswatini", 8],
["🇹🇦", "flag: Tristan da Cunha", 8],
["🇹🇨", "flag: Turks & Caicos Islands", 8],
["🇹🇩", "flag: Chad", 8],
["🇹🇫", "flag: French Southern Territories", 8],
["🇹🇬", "flag: Togo", 8],
["🇹🇭", "flag: Thailand", 8],
["🇹🇯", "flag: Tajikistan", 8],
["🇹🇰", "flag: Tokelau", 8],
["🇹🇱", "flag: Timor-Leste", 8],
["🇹🇲", "flag: Turkmenistan", 8],
["🇹🇳", "flag: Tunisia", 8],
["🇹🇴", "flag: Tonga", 8],
["🇹🇷", "flag: Türkiye", 8],
["🇹🇹", "flag: Trinidad & Tobago", 8],
["🇹🇻", "flag: Tuvalu", 8],
["🇹🇼", "flag: Taiwan", 8],
["🇹🇿", "flag: Tanzania", 8],
["🇺🇦", "flag: Ukraine", 8],
["🇺🇬", "flag: Uganda", 8],
["🇺🇲", "flag: U.S. Outlying Islands", 8],
["🇺🇳", "flag: United Nations", 8],
["🇺🇸", "flag: United States", 8],
["🇺🇾", "flag: Uruguay", 8],
["🇺🇿", "flag: Uzbekistan", 8],
["🇻🇦", "flag: Vatican City", 8],
["🇻🇨", "flag: St. Vincent & Grenadines", 8],
["🇻🇪", "flag: Venezuela", 8],
["🇻🇬", "flag: British Virgin Islands", 8],
["🇻🇮", "flag: U.S. Virgin Islands", 8],
["🇻🇳", "flag: Vietnam", 8],
["🇻🇺", "flag: Vanuatu", 8],
["🇼🇫", "flag: Wallis & Futuna", 8],
["🇼🇸", "flag: Samoa", 8],
["🇽🇰", "flag: Kosovo", 8],
["🇾🇪", "flag: Yemen", 8],
["🇾🇹", "flag: Mayotte", 8],
["🇿🇦", "flag: South Africa", 8],
["🇿🇲", "flag: Zambia", 8],
["🇿🇼", "flag: Zimbabwe", 8],
["🏴󠁧󠁢󠁥󠁮󠁧󠁿", "flag: England", 8],
["🏴󠁧󠁢󠁳󠁣󠁴󠁿", "flag: Scotland", 8],
["🏴󠁧󠁢󠁷󠁬󠁳󠁿", "flag: Wales", 8]
];
